name: university_asset_maintenance
description: A Flutter app for university asset maintenance system.
publish_to: 'none' # this is not a package

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & local DB
  provider: ^6.1.5
  flutter_dotenv: ^5.1.0
  sqflite: ^2.4.2
  path: ^1.9.1

  # Firebase (if youâ€™re using FCM)
  firebase_core: ^2.20.1
  firebase_messaging: ^14.5.0

  # Local notifications
  flutter_local_notifications: ^19.1.0

  # Picking images/videos
  image_picker: ^0.8.9
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.9
  firebase_storage: ^11.7.7
  
  # Supabase client SDK
  supabase: 2.3.0
  supabase_flutter: 2.6.0
  # For generating random IDs
  

  # Needed to run sqflite on web via ffi
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
